services:
  - type: web
    name: photostudio-portfolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
    repo: https://github.com/pashadaevskiy-coder/photostudio.git
    branch: main
